{% set version = "1.1.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-heatmap3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/heatmap3_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/heatmap3/heatmap3_{{ version }}.tar.gz
  sha256: 594c33947b2be2cc8a592075f41a0df2398c892add7d63a15c613a5eeb8fdb69

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-fastcluster
  run:
    - r-base
    - r-fastcluster

test:
  commands:
    - $R -e "library('heatmap3')"  # [not win]
    - "\"%R%\" -e \"library('heatmap3')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=heatmap3
  license: GPL (>= 2)
  summary: An improved heatmap package. Completely compatible with the original R function 'heatmap', and provides more powerful and convenient features.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3  # [unix]
  license_file: {{ environ["PREFIX"] }}\R\share\licenses\GPL-3  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
