travis:
  secure:
    BINSTAR_TOKEN: 1I15SsD/WkoW8EgwFaliPKXkvvCJhtpFMv3J4R2Ao5smXOW2T8oLC6rxy7HedFnAPT/05cvsyH9E2oGbooQcFUQ0NyIbp86Iut0bQWiyYDUflpu2iN37WmpHZhCFggjak52NV+1kpMEaGKU23nAVIH9ATvpoCnCJJcXRi/Hm93q2TedEZ/IcE/e+ax+zJec5Bgje0RIdspFpyw6/c6/9nQoK/eWbmDdVIN0jmN/7l4MZ00fp8S1cqffVXXjdRJEYWvxhiOPAJ0XE3U17Ie6QDO6rwhvlQbNA4P0ULHOOXaKIpMAsQVDbWK4iVUKv57A8CujptefpSr3zpH3qINIfHvjLslVeoGBiSpJoBQEdMiUwV8N+zE0QKnnnHSp+drHjOJAAESr6/CnRIdQxPwI0cHeG6pIyLoffMVbYxW8UqmAf2kldyBuip2EPeOYPxytFybphLOW8A92IWKmhPfwNTwufaq5Fp6eixfan48+3BELqk7+AUNRhy9YgMsww/3bL/T93ECH1yx86Y4GxelJJePU3XsUxk6Msp+J5bhHIbfTcwE2m3bOVO6WsAWxlvZssEpI+6KzR68jHggUGEpAGYwwVjhTaR2mGx10XcNHAVIoBpERm7JEekOcAmxmnWk56O8flvO1jv4YDJJU8rxzava1qaHMMPBA8Q7Zd8GpZUfc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
