travis:
  secure:
    BINSTAR_TOKEN: gpbSavMbPgsEyUzfn1ove5zYpSwfm6eJL1xasJ3QK2XKu7s4I4ffmAf3C6CNihetlDApi/Tdkrgl1JpqWgIeiVRKBrs0CtsmW7Hl4hqpEzYeVPd51/CIN29maL9pls7HoiM7csR2VE7FqVfPsw0XOuDWYL1kIDdxi/sXVBtX9rhjgd6qr2kjD++LlMxi7qpe5FxkFOFoKkoOSTZ+envhHcbkaqWxIgB3qryKw1PTIvvK4msjCqo1c3CgouCGsEAikxf47p6dnSP/70djYpk/a7ax+Boq2dy5nDsRPEZgGxo7BlM5nwzGvjAGbUA/AOz4EBSMQWgkzL+D5ZGB3Lt3qjs0SQsi62hr2XQrt5wq0cmGkLo+x8eyqjyJb4zM8yOr6MIQy8EdjDo2A2lIqmmOafsnW5rQixPu5LmXmkNCMU6G2V1QZXRmX0p+VnpWbAFqJzwXi9nYygsqptTj83ozy1LC7vFSJvHtyrtfhzIIgstqZWKAIOwNzASCrgQAplcG1ae8lwycdLhuxywydKM8eTmrX+ZxHCajrpLYbEvKYqK7pRC3V+CTWX4pemsWoQ8GtvK3V7s8DN0dTrWJELOHHYcrLnp0+Rr2dYJUEbzYmV4ccDyA677XVQ2UkBEdENaDxpVMPJEuCz4Y9PV4hHRUnN0A/GUbC63bWiiSTe3lemA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
