appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: aTpVNBYg/dooDGE9BM11w1MOMYVj4mv6C0ZYZBmHuwyp2663XBGk+yAd3I3WOuu5L/liJAZUkKq6V4PywH9RcJHtEu7vRUmSH5zntS7TXVMs7doVd8KdJzX+clfZA/A27tx1p4PuDcmdUA2fUtULAGsmmYjjEHrNCHGH0BLFUzS3x/IFVujXgfcCOJCt/zdW2iq/P0dim3JOvZQJS+24QVYAs084mVc8iTnbcSuY0smEZws53Du64MXZeLGskeduyeCRqdZNfUvQuDg45CO0Jy7s43KanDyhHBspKhKHH8cUWe3tqEurLNna1f0QopJhld6UwlI/vVQ9tnAbMkLD4k9WxGhviAwklnS2O1GJTARFUoUqhgu8bnCQlqenz7Rg4z16ACQ+qHulg+xRqYkcn0eF0p7tLvuEB7XWOcLShQ9rqfx+WOdjBatWP4PZMWDTogGF22NEsix4TryHFYxS26mwS84nNVPmxqhI5RG8+LGxGjHcAP9PK/sotv7MenjAgTnMX+9lRv1CA7IwESGWK8TvZZW1tk4bAHWKKQ9i0gUr8QVoC4NhCyFlaNZmAcfeZamS+hJ1k5t/vTK71JrseczHmRUmo91OHsQJ7oWg57HQGt+m1ymDrS9wXzfZ5J2tQcC3cfSSdLJJX30P0zB1DRGgFhEXAzbkhXmQe+a1WP4=}
