travis:
  secure:
    BINSTAR_TOKEN: ydaGQvRcCT9f75EQ1L/rUGynijUghVNw5OH6yRBsMkfCs1mIqXRzL2RXFBoU/hB0kEmoONyyzRp64exUryTn7AqFtyN8tpP/Wl4V75neA7471MLErGmmAvdWQSrsj7giN81PnbEeHUce6o6WmMCUVOZAb+5/9ZDLSSbGJ7jkF2jMTrJZkokvhGNpbhsWvbM/yGWgA9QfoHO/Z1iPHPKscNH4TRLSTovwYLPLS/aceNdhYHNNyIo3IDdaMh0J5GeMgAR+IqIkbDn2d+NpACvPgaw6+yuCAytqXXuanml6qThlmSS/EeIJFhu9ZhXEhGrKb0PG4eN96n4gkYHcK8sRMDMoObK42ZZFxd0cf2SkpvsQqxddx8t1aF5lggyaG6cRfKZb+up7we2UINacpAL/oqxWn968kV1Dp/XUXzhbOfna+LyNNPtwnU9GJsaKXkOhAJTq+fU6gzEMXzDGhNx7a8m8JGmeNdn5xiPByZG4C8HMV8ZK/pVmQ4ta923ECJN7c5Xb6q8hoUxSct4vGUaBX3/ERqcNUbLchQUCT0Z074Z1oKX9j6Suu/lLNoh24YnhnfJEJd4TiJX+11T5mQlXdJR1QSEzjEI0A/INrvsHUtrO2Uo1NGUNTqazalxW27wW2Reb+8FMej3oSEtA1nkVHc91HGktUAl5Ytg9VQ0TgDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
