travis:
  secure:
    BINSTAR_TOKEN: LnfnDQaL39y5r9I24Uipu/NqBC0DkVMBOldMsSF8M+p1Las6bxBYzbOr9ZJ/X0WlprbKmylBbkyLQPEch4Y8VZY/0BZsCgCWdwr/j07eE8lOavqjlT/J5J0hhORSZPDO7mxzzvXDB8s4+NXstJCAs+Kl+cL8txh69aDd7/3cXNenaoTYNsI2MLKzaDdmkQtwN/ZGnKxl3LSg1fuPWH6kRre5fbqRK+PSnrjMTfyV09M60vebNyeZl41fyUJG/rTkfb9I3e7xjNI60EQJnRLA6X7V/BvE18PAj58XWXndbNcBPV90X6OipDWJG7etdt7GqpdyLJJB9xKNg+LIZoFcqtFc8lzs19hu9vpiU/GLvsYem4Z6SwiSa52x3a+dgHtu43NEPIu3PfUzo8663UXcsgopmpFLu6pvqpQrmisMndayltrLK6wqmmy2s3FAM5ugqYH3P6YRdOFk4LcJIMqFp88rU8uvvE3JGyNEP1dd4DemPYbG/bcyoRlYiEyc+y8VhsU0fQF9vnA5W+h5HWxs98QPC+ewvM/VyRx9RpFJs52cZzQ7joZ5qZ7U5IiSEL8nBjL7mDIPtpOcUj3P/8LXMJVVVXfjPIgmk/8xThlC1ZXgSz7wdF44DxO58NxbLCwV72RD6pjtWS37aa6m/olmkhUjX+l+6Eqz6b0MWzY0kuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
